server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-catalog
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      user: root
      password: root
      uri: mongodb://localhost:27017/catalog-dev

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuro el circuit breaker dentro de catalog. Considero que es el mas utilizado debido
# a que todas las request tienen que pasar por este, ya sean de movies o de series.

#resilience4j:
#  retry:
#    configs:
#      default:
#        max-retry-attempts: 3
#        wait-duration: 1s
#        retry-exceptions:
#          - java.io.IOException
#          - java.net.SocketTimeoutException
#      instances:
#        retryCard:
#          base-config: default
#          max-retry-attempts: 5
#          wait-duration: 2s
#          retry-exceptions:
#            - java.net.ConnectException

# circuitbreaker:
#  configs:
#    default:
#      register-health-indicator: true
#      sliding-window-size: 10
#      minimum-number-of-calls: 5
#      permitted-number-of-calls-in-half-open-state: 3
#      wait-duration-in-open-state: 30s
#      automatic-transition-from-open-to-half-open-enabled: true
#      failure-rate-threshold: 40
#  instances:
#    configCard:
#      base-config: default
#      sliding-window-type: COUNT_BASED
#      sliding-window-size: 10
#      wait-duration-in-open-state: 1m
#      failure-rate-threshold: 40

resilience4j.retry:
  instances:
    retryCatalog:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException

resilience4j.circuitbreaker:
  instances:
    clientCatalog:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 30s
      failureRateThreshold: 40
      eventConsumerBufferSize: 10



