server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-catalog
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/catalog-dev?authSource=admin

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuro el circuit breaker dentro de catalog. Considero que es el mas utilizado debido
# a que todas las request tienen que pasar por este, ya sean de movies o de series.

resilience4j.retry:
  instances:
    retryCatalog:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException

resilience4j.circuitbreaker:
  instances:
    clientCatalog:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 30s
      failureRateThreshold: 40
      eventConsumerBufferSize: 10



