server:
  port: ${PORT:${SERVER_PORT:8080}}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mscatalog
          uri: lb://api-catalog
          predicates:
            - Path=/catalog/**
        - id: msmovie
          uri: lb://api-movie
          predicates:
            - Path=/movie/**
        - id: msserie
          uri: lb://api-serie
          predicates:
            - Path=/serie/**
info:
  app:
    name: ${spring.application.name}
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway